# Generated by Django 3.1.1 on 2020-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='b1',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name=[models.CharField(max_length=225), models.CharField(default=None, max_length=225), models.CharField(default=None, max_length=225), models.CharField(default=None, max_length=225)]),
        ),
    ]
