# Generated by Django 3.1.1 on 2020-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanz', '0002_auto_20200918_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='b2',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='post',
            name='b3',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='post',
            name='b4',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name=[models.CharField(max_length=225), models.CharField(max_length=225), models.CharField(max_length=225), models.CharField(max_length=225)]),
        ),
    ]
