# Generated by Django 3.1.1 on 2020-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanz', '0003_auto_20200918_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='b1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='b2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='b3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='b4',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
