# Generated by Django 3.1.1 on 2020-09-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanz', '0004_auto_20200918_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u1', models.URLField(max_length=250)),
                ('u2', models.URLField(max_length=250)),
                ('u3', models.URLField(max_length=250)),
                ('u4', models.URLField(max_length=250)),
            ],
        ),
    ]
